### ISSUE TITLE
Can the animation change selected view from left to right?

### ISSUE THREAD

**Issue by kingyau** [bardonadam/SlidingTabBar#1]
The animation of changing selected view in SlidingTabBar only has  from right to left, but is it possible to change view from left to right?

**Comment by bardonadam** [comment]
Sorry for late answer but anyway good idea, I will update it and add in new version ;)

**Comment by kingyau** [comment]
thanks for notes. I have already make it. It is quite easy that you just need to pass the fromIndex and toIndex in func tabBarController(tabBarController: UITabBarController, animationControllerForTransitionFromViewController fromVC: UIViewController, toViewController toVC: UIViewController)  of TabBarController.swift. Then calculate it in your SlidingTabAnimationController.swift, for example, if fromIndex > toIndex, the animation should be right to left and left to right if lesser.

**Comment by bardonadam** [comment]
yes, it wasn't matter of difficulty, I was just busy 😉 anyway it's added now in new version
