### ISSUE TITLE
tabBarView doesn't show up

### ISSUE THREAD

**Issue by xaksis** [bardonadam/SlidingTabBar#5]
I am trying to replace the existing tab bar with slidingTabBar. I did the following: 

```
func setupTabs(){
        //hide the default tabbar
        self.tabBar.hidden = true
        self.selectedIndex = 0

        //initialize the fancy tabbar
        tabBarView = SlidingTabBar(frame: self.tabBar.frame, initialTabBarItemIndex: self.selectedIndex)
        tabBarView.tabBarBackgroundColor = Styles.brandPrimary
        tabBarView.tabBarItemTintColor = Styles.brandPrimaryLight
        tabBarView.selectedTabBarItemTintColor = UIColor.whiteColor()
        tabBarView.selectedTabBarItemColors = [Styles.softYellow, Styles.softYellow, Styles.softYellow]
        tabBarView.slideAnimationDuration = 0.6
        tabBarView.datasource = self
        tabBarView.delegate = self
        tabBarView.setup()

        self.delegate = self

        print(tabBarView.frame)

        self.view.addSubview(tabBarView)
    }
```

The original tab bar is hidden, but the subview never shows up. What might I be missing here?

**Comment by xaksis** [comment]
so the problem was that `self.tabBar.frame` did not have the correct y coordinate and was actually creating the subview right outside the visible frame. to get the correct y coordinate for the sliding tab bar, we have to subtract the status bar + nav bar height from the y coordinate of tabBar. here's a function I wrote to do just that: 

``````
    func getCorrectFrame()->UIView{
        let navigationBarHeight: CGFloat = UIApplication.sharedApplication().statusBarFrame.height +
            self.navigationController!.navigationBar.frame.height
        let y: CGFloat = self.tabBar.frame.minY - navigationBarHeight
        let v = UIView(frame: CGRectMake(0, y, self.tabBar.frame.size.width, self.tabBar.frame.size.height))
        return v
    }```
``````

**Comment by bardonadam** [comment]
That's weird, it always worked for me by default. Have you checked example project?

**Comment by xaksis** [comment]
Hey yeah, I'm not sure why I needed to subtract the navigation bar height. I needed to use it with a pre-existing project so I haven't spent a lot of time noting the differences between that and the example project. Once I get some free cycles I'll take a look. Let me also take a moment to thank you! great work!

**Comment by bardonadam** [comment]
Thank you :)
