### ISSUE TITLE
Hiding sliding tab bar inside inner views

### ISSUE THREAD

**Issue by OsamaBinBashir** [bardonadam/SlidingTabBar#6]
Hi ...  I am using your sliding tab bars .  I want to hide them completely when i segues to any other inner view to maintain the single navigation stack . Can you please tell me how can i achieve this . Thanks in advance

**Comment by bardonadam** [comment]
Hi, since tabBarView is subclass of UIView, you should be able to hid it with `self.tabBarView.isHidden = true`
